# fly.toml app configuration file generated for red-badger-animal-hunt on 2024-01-09T15:47:01Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "red-badger-animal-hunt"
primary_region = "lhr"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
